name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Force reinstall pip
      run: |
        python -m ensurepip --upgrade
        python -m pip install pip==24.3.1 --force-reinstall

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: YOLOAppService
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
